SzFMV2018-Osz/AutomatedCar-B

pom.xml
src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
src/main/java/hu/oe/nik/szfmv/automatedcar/engine/CarEngine.java
src/main/java/hu/oe/nik/szfmv/automatedcar/engine/StandardCarEngine.java
src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/PowertrainSystem.java
src/test/java/hu/oe/nik/szfmv/powertrain/PowertrainSystemUpdateEngineStateTest.java

-Engine model
-RPM calculated based on car speed and wheel radius
-Automated gear shifting

Car engine model, Rpm calculation

---

src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
src/main/java/hu/oe/nik/szfmv/automatedcar/engine/CarEngine.java
src/main/java/hu/oe/nik/szfmv/automatedcar/engine/CarEngineType.java
src/main/java/hu/oe/nik/szfmv/automatedcar/engine/GearBox.java
src/main/java/hu/oe/nik/szfmv/automatedcar/engine/StandardCarEngineType.java
src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/PowertrainSystem.java
src/test/java/hu/oe/nik/szfmv/engine/CarEngineTest.java
src/test/java/hu/oe/nik/szfmv/engine/GearBoxTest.java
src/test/java/hu/oe/nik/szfmv/powertrain/PowertrainSystemUpdateEngineStateTest.java

-Refactored RPM calculation and automated gearshifting

RPM calculation fixes

---

src/main/java/hu/oe/nik/szfmv/Main.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/IUserInput.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/KeyboardUserInput.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/UserInputProvider.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/enums/Direction.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/enums/Gear.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/enums/InputType.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/enums/PedalType.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/eventhandlers/IIndicationEventHandler.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/eventhandlers/IPedalEventHandler.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/eventhandlers/IShiftingEventHandler.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/eventhandlers/ISteeringEventHandler.java
src/main/resources/config.toml
src/test/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/KeyboardUserInputTest.java
src/test/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/UserInputProviderTest.java

- provides interface for the user inputs
- notifies the subscribed components of business events
- key roles defined in the configuration file

Keyboard input handler

---

src/main/java/hu/oe/nik/szfmv/automatedcar/BrakingForces.java
src/main/java/hu/oe/nik/szfmv/automatedcar/CarPhysics.java
src/test/java/hu/oe/nik/szfmv/physics/AirResistanceTest.java

Added a physics class and constant air resistance calculator function

Added a physics class and constant air resistance calculator function

---

src/main/java/hu/oe/nik/szfmv/automatedcar/BrakingForces.java
src/test/java/hu/oe/nik/szfmv/physics/BrakeForceTest.java

added a maxBrakeForce constant and a function that calculates a linear braking force.

Added Linear Braking.

---

src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/VirtualFunctionBus.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/IndicationPacket.java
src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/InputManager.java
src/test/java/hu/oe/nik/szfmv/automatedcar/bus/packets/IndicationPacketTest.java
src/test/java/hu/oe/nik/szfmv/automatedcar/bus/packets/UserInputDummy.java

- Indication packet available on the Virtual Function Bus
- Indicator position changes on key push

Feature indicator controller

---

src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/GraduallyChangeable.java
src/test/java/hu/oe/nik/szfmv/automatedcar/bus/packets/GraduallyChangeableTest.java

Util class for gradually changeable variable's value determination

---

src/main/java/hu/oe/nik/szfmv/automatedcar/bus/VirtualFunctionBus.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/GearPacket.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/KeyboardUserInput.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/enums/Gear.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/eventhandlers/IShiftingEventHandler.java
src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/InputManager.java
src/test/java/hu/oe/nik/szfmv/automatedcar/bus/packets/GearPacketTest.java
src/test/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/KeyboardUserInputTest.java

Changes: see below
Sender team: B3
Issues: #23
Added functionalities
controller that handles shifting
Other
Tests added to the controller

Team b3 feature gearpacket

---

src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
src/main/java/hu/oe/nik/szfmv/automatedcar/BrakingForces.java
src/main/java/hu/oe/nik/szfmv/automatedcar/TractionForce.java
src/main/java/hu/oe/nik/szfmv/automatedcar/engine/CarEngine.java
src/main/java/hu/oe/nik/szfmv/automatedcar/engine/CarEngineType.java
src/main/java/hu/oe/nik/szfmv/automatedcar/engine/StandardCarEngineType.java
src/test/java/hu/oe/nik/szfmv/engine/CalculateDrivingTorqueTest.java
src/test/java/hu/oe/nik/szfmv/engine/CarEngineCalculateEngineTorqueTest.java
src/test/java/hu/oe/nik/szfmv/engine/CarEngineUpdateRpmTest.java
src/test/java/hu/oe/nik/szfmv/engine/GearBoxTest.java
src/test/java/hu/oe/nik/szfmv/physics/TractionForceTest.java

Torque calculations
Traction force calculation from driving torque

#56 traction force

---

src/main/java/hu/oe/nik/szfmv/automatedcar/BrakingForces.java
src/test/java/hu/oe/nik/szfmv/physics/BrakeForceTest.java

Calculating rolling resistance

Calc Rolling resistance

---

src/main/java/hu/oe/nik/szfmv/automatedcar/bus/VirtualFunctionBus.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/GraduallyChangeable.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/SteeringWheelPacket.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/interfaces/IGraduallyChangeable.java
src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/InputManager.java
src/test/java/hu/oe/nik/szfmv/automatedcar/bus/packets/GraduallyChangeableTest.java
src/test/java/hu/oe/nik/szfmv/automatedcar/bus/packets/SteeringWheelPacketTest.java
src/test/java/hu/oe/nik/szfmv/systemcomponents/InputManagerTest.java

Issue: #59 
- Steering wheel position can be changed and appears on the virtual function bus
- change in GraduallyChange util class to make the dependent components testable 
- tests for steering wheel controller
-test for input manager

Feature steering wheel controller

---

src/main/java/hu/oe/nik/szfmv/visualization/Dashboard.java
src/main/java/hu/oe/nik/szfmv/visualization/elements/CircleCalculator.java

meter design ready, placed on dashboard, refreshes the value on change

feature(rpm and speed meter): ready

---

src/main/java/hu/oe/nik/szfmv/visualization/Dashboard.java

Changes: see below
Sender team: B3
Issues: #27 
gear UI element added to dashboard

add gear label to dashboard

---

src/main/java/hu/oe/nik/szfmv/automatedcar/engine/GearBox.java

- Fixed nullpointer exception on startup

B4 nullpointerfix

---

src/main/java/hu/oe/nik/szfmv/visualization/Dashboard.java
src/main/java/hu/oe/nik/szfmv/visualization/Elements/PedalBar.java
src/main/java/hu/oe/nik/szfmv/visualization/elements/CircleCalculator.java
src/main/java/hu/oe/nik/szfmv/visualization/elements/IndexArrow.java

Lehet később változtatni rajta, ha nem jó, jelenleg úgy működik, hogy majd meghívjuk a start metódusát mikor kell, akkor elkezd tickelni magától, a rajzon villog majd sárgán / fehéren fél secenként, egészen addig míg meg nem állítja valami, azaz míg meg nem hívjuk a stop metódusát.
Javítottam még a fordulatszám mérőn, 5 számot ír ki csak. Meg kicsit feljebb raktam a sebességi fokozatot a boardon.

feature(index visualization): ready

---

src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/GraduallyChangeable.java
src/test/java/hu/oe/nik/szfmv/automatedcar/bus/packets/GraduallyChangeableTest.java

-divide by zero exception in GraduallyChangeable on immediate value change
-test change determination

Fix gradually changeable dividebyzero bug

---

src/main/java/hu/oe/nik/szfmv/Main.java
src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/VirtualFunctionBus.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/DashboardPacket.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/interfaces/IReadOnlyDashboardPacket.java
src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/DashboardManager.java
src/main/java/hu/oe/nik/szfmv/visualization/Dashboard.java
src/main/java/hu/oe/nik/szfmv/visualization/elements/IndexArrow.java

To provide the dashboard GUI with the necessary data through the VFB.

Dashboard Manager system component

---

src/main/java/hu/oe/nik/szfmv/visualization/Dashboard.java

- no hidden gear states anymore

fix gear label display

---

src/main/java/hu/oe/nik/szfmv/visualization/CourseDisplay.java

The irrelevant parts must be removed!
- Egocar now turns left pressing left arrow #112 
- ...
- Flux capacitor has been implemented #112 
- ...
- getWorldObjectReferencePoint no longer returns the top-left corner
but the centroid #112 
- ...
- e.g. Tests added to powertrain
- Input handling was refactored
- ...

Scalefactor módosítása, üzemi scalere optimalizálása

---

src/test/java/hu/oe/nik/szfmv/environment/WorldObjectTest.java
src/test/java/hu/oe/nik/szfmv/environment/WorldTest.java
src/test/java/hu/oe/nik/szfmv/environment/XmlObjectTest.java

Create:
- WorldObjectTest
- WorldTest
- XmlObjectTest

WorldObjectTest, WorldTest, XmlObjectTest

---

src/main/java/hu/oe/nik/szfmv/Main.java
src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/IndicationPacket.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/PedalPacket.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/interfaces/IGraduallyChangeable.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/interfaces/IReadOnlyDashboardPacket.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/interfaces/IReadonlyGearPacket.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/interfaces/IReadonlyIndicationPacket.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/interfaces/IReadonlySteeringPacket.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/IUserInput.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/KeyboardUserInput.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/UserInputProvider.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/eventhandlers/IIndicationEventHandler.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/eventhandlers/IPedalEventHandler.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/eventhandlers/IShiftingEventHandler.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/eventhandlers/ISteeringEventHandler.java
src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/InputManager.java
src/main/java/hu/oe/nik/szfmv/visualization/elements/IndexArrow.java
src/main/java/hu/oe/nik/szfmv/visualization/elements/PedalBar.java

- add missing field to the _Main_ function
- fix most of the style changes in classes in connection with HMI

Fix build bug, style changes

---

src/main/java/hu/oe/nik/szfmv/visualization/elements/CircleCalculator.java

Fixed causes of Checkstyle and IDE warnings
- CircleCalculator class

Team B3: fix - circle calculator class refactor

---

pom.xml
src/main/java/hu/oe/nik/szfmv/Main.java

Team b3 fix correct bugfix

---

src/main/java/hu/oe/nik/szfmv/Main.java
src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/VirtualFunctionBus.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/DisplayableSensorPacket.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/SensorPacket.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/interfaces/IReadonlyDisplayableSensorPacket.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/interfaces/IReadonlySensorPacket.java
src/main/java/hu/oe/nik/szfmv/automatedcar/sensor/SensorType.java
src/main/java/hu/oe/nik/szfmv/common/enums/Coordinate.java
src/test/java/hu/oe/nik/szfmv/automatedcar/bus/packets/DisplayableSensorPacketTest.java
src/test/java/hu/oe/nik/szfmv/automatedcar/bus/packets/SensorPacketTest.java

-packet for sensor detected objects
-packet for sensor visualization
-test for sensor packet
-test for displayable sensor packet

Team b3 feature sensor packets

---

src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/CameraPacket.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/interfaces/ICameraPacket.java

camera vb packet interface létrehozása és implementálása
camera vb packet interface létrehozása és implementálása
Jelenleg 5 dolgot tartalmaz egy packet: 
A sávok számát
A aktuális sáv széléttől való távolságot mind két irányba
A legközelebbi táblát
És hogy melyik sávban van egy boolean több szombolizálja balról jobbra kell feltötlteni a true érték szimbolizálja az aktuális sávot.

#163 camera vb packet

---

src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/CameraPacket.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/interfaces/ICameraPacket.java
src/main/java/hu/oe/nik/szfmv/automatedcar/sensor/Camera.java
src/main/java/hu/oe/nik/szfmv/environment/World.java

TeamB4
camera példányosítás
nullpointer fix
CameraPacket bővítése

Camera fixes

---

src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/VirtualFunctionBus.java
src/main/java/hu/oe/nik/szfmv/automatedcar/sensor/radar/Radar.java

Radar as systemcomponent
Radar in car

Radar in automatedcar

---

src/main/java/hu/oe/nik/szfmv/automatedcar/sensor/ISensor.java
src/main/java/hu/oe/nik/szfmv/automatedcar/sensor/SensorBase.java
src/main/java/hu/oe/nik/szfmv/automatedcar/sensor/UltraSoundSensor.java

The irrelevant parts must be removed!
- Egocar now turns left pressing left arrow #ISSUE-ID
- ...
- Flux capacitor has been implemented #ISSUE-ID
- ...
- getWorldObjectReferencePoint no longer returns the top-left corner
but the centroid #ISSUE-ID
- ...
- e.g. Tests added to powertrain
- Input handling was refactored
- ...

ultrasound sensor implementation

---

src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/IUserInput.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/KeyboardUserInput.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/userinput/eventhandlers/ISensorDebugEventHandler.java
src/main/java/hu/oe/nik/szfmv/automatedcar/sensor/Camera.java
src/main/java/hu/oe/nik/szfmv/automatedcar/sensor/SensorDebug.java
src/main/resources/config.toml
src/test/java/hu/oe/nik/szfmv/automatedcar/bus/packets/UserInputDummy.java

sensor debug mostly works, cannot render stuff.

Sensordebug rebased

---

src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
src/main/java/hu/oe/nik/szfmv/automatedcar/engine/TurningHandler.java
src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/PowertrainSystem.java
src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/SteeringSystem.java
src/main/java/hu/oe/nik/szfmv/environment/WorldObject.java
src/test/java/hu/oe/nik/szfmv/engine/TurningHandlerTest.java

Világ szétesés fix. 

---

src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/DashboardPacket.java
src/main/java/hu/oe/nik/szfmv/automatedcar/bus/packets/interfaces/IReadOnlyDashboardPacket.java
src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/DashboardManager.java
src/main/java/hu/oe/nik/szfmv/visualization/Dashboard.java

Speed and rpm displayed on the dashboard
